SELECT * FROM AIRLINE.PASSENGER;
SELECT * FROM AIRLINE.PASSENGER WHERE "sex" = 'f';
SELECT * FROM AIRLINE.PASSENGER WHERE "sex" = 'm';
SELECT "name", "surname", "secondname" FROM AIRLINE.PASSENGER RIGHT JOIN AIRLINE.TICKET ON AIRLINE.PASSENGER.passenger_id = AIRLINE.TICKET.passenger_id WHERE AIRLINE.TICKET.sale_date > '2022-10-22';